In [2]:
(10 + 5)/3

5.0

In [10]:
var1 = 'hello'

In [13]:
var1

'hello'

In [12]:
print(var1)

hello


In [11]:
type(var1)

str

In [14]:
x = [1,2,3,4,5,6]

In [15]:
x

[1, 2, 3, 4, 5, 6]

In [16]:
type(x)

list

In [17]:
a = 7

In [18]:
x.append(a)

In [19]:
x

[1, 2, 3, 4, 5, 6, 7]

In [20]:
x.pop(0)

1

In [21]:
x

[2, 3, 4, 5, 6, 7]

In [22]:
x.append(100)
x

[2, 3, 4, 5, 6, 7, 100]

In [25]:
x.reverse()
x

[100, 7, 6, 5, 4, 3, 2]

In [27]:
x.append(1)
x

[100, 7, 6, 5, 4, 3, 2, 1]

In [28]:
y = [5,True,7.6,'Hello']
y

[5, True, 7.6, 'Hello']

In [29]:
#comments

In [30]:
y[2] = 'Mil'
y

[5, True, 'Mil', 'Hello']

In [31]:
t = (5,True,7.6,'Hello')
t

(5, True, 7.6, 'Hello')

In [33]:
t[2] = "2Mil"

TypeError: 'tuple' object does not support item assignment

In [34]:
y

[5, True, 'Mil', 'Hello']

In [35]:
y[3]

'Hello'

In [36]:
len(y)

4

In [37]:
#press 'l' does what?

In [38]:
y[-1]

'Hello'

In [39]:
n = 7
n

7

In [41]:
if (n > 0):
    print('Nro Positivo')
if (n < 0):
    print('Nro Negativo')
else:
    print('Nro Zero')

Nro Positivo
Nro Zero


In [40]:
#iddent matters in python

In [42]:
n = 0
n

0

In [43]:
if (n > 0):
    print('Positivo')
elif (n < 0):
    print('Negativo')
else:
    print('Zero')

Zero


In [44]:
# h for shortcuts

In [47]:
seq = [0,1,2,3,4,5,6,7,8,9]
seq

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
for i in seq:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [51]:
seq2 = [156315,11210,2002,3123,41561,515634,60022,102,70231,8008,900,54156]
seq2

[156315, 11210, 2002, 3123, 41561, 515634, 60022, 102, 70231, 8008, 900, 54156]

In [52]:
for i in seq2:
    print(i)

156315
11210
2002
3123
41561
515634
60022
102
70231
8008
900
54156


In [55]:
i = 0
while(i <= 8):
    print(i)
    i += 1

0
1
2
3
4
5
6
7
8


In [54]:
# i = i + 1 ; i += 1

In [56]:
l1 = [4, 7, 9]
l2 = [11, 3, 8]

In [57]:
l1 + l2

[4, 7, 9, 11, 3, 8]

# aperte 1 para escrever na célula

## 2 para escrever assim

In [64]:
c1 = 'Hello'
c2 = ' '
c3 = 'World'
c4 = '!'

In [66]:
c1 + c2 + c3 + c4

'Hello World!'

In [68]:
import numpy as np

In [69]:
numpy

<module 'numpy' from '/home/saul/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>

In [72]:
np

<module 'numpy' from '/home/saul/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>

In [62]:
# a insert cell above, b insert cell bellow

In [70]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [71]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [73]:
import math

In [74]:
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [76]:
# 'shift+tab' na função para ssaber sobre ela

In [56]:
l1 = [4, 7, 9]
l2 = [11, 3, 8]

In [77]:
arr1 = np.array(l1)
arr2 = np.array(l2)

In [79]:
arr1

array([4, 7, 9])

In [80]:
arr2

array([11,  3,  8])

In [82]:
arr1*arr2

array([44, 21, 72])

In [84]:
np.dot(arr1,arr2)

137

In [85]:
np.append(arr1,5)

array([4, 7, 9, 5])

In [91]:
intervalo = range(0,10)
intervalo

range(0, 10)

In [92]:
for val in intervalo:
    print(val)

0
1
2
3
4
5
6
7
8
9


In [99]:
np.arange(0,11,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [101]:
x = np.linspace(0,11,3)
x

array([ 0. ,  5.5, 11. ])

In [102]:
np.sqrt(x)

array([0.        , 2.34520788, 3.31662479])

In [103]:
np.exp(x)

array([1.00000000e+00, 2.44691932e+02, 5.98741417e+04])

In [104]:
# dicionário:   {'chave':'valor','chave':'valor','chave':'valor'}

In [118]:
# deixa várias "variáveis" em uma só

In [115]:
d = {'c1': 567, 'c2': 12.56, 'c3': 'Hello', 'c4': np.arange(0,5,0.7)}
d

{'c1': 567,
 'c2': 12.56,
 'c3': 'Hello',
 'c4': array([0. , 0.7, 1.4, 2.1, 2.8, 3.5, 4.2, 4.9])}

In [116]:
d['c3']

'Hello'

In [117]:
d.get('c3')

'Hello'